CONFIG_IQS7211E=y
CONFIG_IQS7211E_SCROLLER_INERTIA=y
CONFIG_IQS7211E_TAP_EDGE_MARGIN_PERMILLE=80
CONFIG_IQS7211E_SCROLLER_HWHEEL_ZONE_MIN_PERMILLE=0
CONFIG_IQS7211E_SCROLLER_HWHEEL_ZONE_MAX_PERMILLE=150
CONFIG_IQS7211E_SCROLLER_HWHEEL_ZONE_FROM_BOTTOM=n
